[workspace]
resolver = "2"

members = [
  "day-*",
  "util",
  "xtask",
]

[workspace.dependencies]
anyhow = "1.0.75"
pretty_assertions = "1.4.0"
rstest = "0.18.2"
rstest_reuse = "0.6.0"
divan = "0.1.3"
nom = "7.1.3"
nom-supreme = "0.8.0"
itertools = "0.12.0"
rayon = "1.8.0"
petgraph = "0.6.4"
