set dotenv-load

# Run a specific day and part.
run day="$DAY" part="$PART": 
  @echo "{{BOLD}}go run day-{{day}}/part{{part}}/part{{part}}.go day-{{day}}{{NORMAL}}" 1>&2
  @go run day-{{day}}/part{{part}}/part{{part}}.go day-{{day}}

# Run tests for a specific day and part.
test day="$DAY" part="$PART" flags="": 
  @echo "{{BOLD}}go test {{flags}} `pwd`/day-{{day}}/part{{part}}{{NORMAL}}" 1>&2
  @go test {{flags}} `pwd`/day-{{day}}/part{{part}}

# Generate a new day folder with starter binary and test files.
gen day:
  mkdir day-{{day}} && cp -r ./template/* ./day-{{day}}/ 

rn:
  echo 'This is a recipe!'

# this is a comment
an:
  @echo 'This is another recipe.'