# Run a specific day and part.
run day part: 
  go run day-{{day}}/part{{part}}/part{{part}}.go day-{{day}}

# Run tests for a specific day and part.
test day part flags="": 
  go test {{flags}} `pwd`/day-{{day}}/part{{part}}

# Generate a new day folder with starter binary and test files.
gen day:
  mkdir day-{{day}} && cp -r ./template/* ./day-{{day}}/ 
